// ─────────────────────────────────────────────────────────────────────────────
// SpatiumAI — Resolution Types
// Represents AI-generated fix options for each constraint violation.
// Generated by spatiumai-ai service (Python/LangChain + Claude API).
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single AI-generated resolution option for a constraint violation.
 * Every element ID referenced in `affectedElementIds` MUST exist in the
 * spatial graph — validated server-side before returning to client.
 */
export interface ResolutionOption {
  /** 0-indexed position in the options array */
  index: number;

  /**
   * Short title shown in the UI.
   * E.g. "Relocate toilet to NW zone"
   */
  title: string;

  /**
   * Full Ayush-quality plain English description.
   * E.g. "Move the toilet to the NW zone. This resolves the Vastu violation
   * for NE placement. Adjust the plumbing chase by approximately 1.2 m."
   */
  description: string;

  /**
   * Specific geometric change in measurable terms.
   * E.g. "Shift east wall of Bedroom 2 by 300mm east. Reduce Corridor width from 1.8m to 1.5m."
   */
  spatialChange: string;

  /**
   * IDs of rooms, walls, or openings from the SpatialGraph that this resolution modifies.
   * Validated against the spatial graph — any ID not found causes this option to be discarded.
   */
  affectedElementIds: string[];

  estimatedImpact: {
    /** Expected change in overall compliance score (+18 means goes up by 18 points) */
    complianceScoreDelta: number;
    /** Constraint codes that this resolution is expected to fix */
    resolvedConstraints: string[];
    /** Constraint codes that might be introduced by this change (trade-offs) */
    potentialNewConflicts: string[];
  };

  confidence: 'high' | 'medium' | 'low';

  /** Ayush quality rating — populated after review, not during generation */
  ayushRating?: 'excellent' | 'good' | 'needs_work' | 'wrong';
}

/**
 * The complete set of resolution options for a single constraint violation.
 * Returned by POST /resolve on the spatiumai-ai service.
 * Stored in the `resolutions` table as resolution_options JSONB.
 */
export interface ResolutionSet {
  evaluationId: string;
  constraintId: string;
  constraintCode: string;

  /** Formatted conflict description sent to LLM for context */
  conflictDescription: string;

  /** 2–3 options, ordered by estimated impact descending */
  options: ResolutionOption[];

  generatedAt: string; // ISO 8601
  modelUsed: string; // e.g. "claude-sonnet-4-6"
  tokensUsed?: number; // for cost tracking

  /** Which option the architect selected */
  acceptedOptionIndex?: number;
  acceptedAt?: string;
  acceptedBy?: string; // user ID
}

// ─────────────────────────────────────────────────────────────────────────────
// Resolve Request/Response (spatiumai-ai service internal API)
// ─────────────────────────────────────────────────────────────────────────────

export interface ResolveRequest {
  evaluationId: string;
  constraintId: string;
  constraint: {
    code: string;
    domain: string;
    severity: string;
    plainDescription: string;
    resolutionHints: string[];
  };
  conflict: {
    affectedElementIds: string[];
    measuredValue?: number;
    thresholdValue?: number;
    unit?: string;
  };
  /** Anonymized spatial context — no project names, client names, location */
  spatialContext: {
    roomCount: number;
    totalAreaSqm: number;
    affectedRooms: Array<{
      id: string;
      spaceType: string;
      areaSqm: number;
      adjacentTo: string[];
    }>;
  };
}

export interface ResolveResponse {
  resolutionSet: ResolutionSet;
  processingMs: number;
}
